// ------------------------------------------------------------------------------
//   <copyright from='2010' to='2015' company='THEHACKERWITHIN.COM'>
//     Copyright (c) TheHackerWithin.COM. All Rights Reserved.
// 
//     Please look in the accompanying license.htm file for the license that 
//     applies to this source code. (a copy can also be found at: 
//     http://www.thehackerwithin.com/license.htm)
//   </copyright>
// -------------------------------------------------------------------------------
namespace DirectEve
{
    public enum DirectCmd
    {
        OpenJournal,
        OpenHelp,
        OpenStationManagement,
        OpenScanner,
        OpenMapBrowser,
        OpenHangarFloor,
        OpenShipHangar,
        OpenBrowser,
        OpenMarket,
        PrintScreen,
        OpenMonitor,
        OpenFpsMonitor,
        OpenLpstore,
        OpenFitting,
        CmdToggleMap,
        WinCmdToggleWindowed,
        CmdResetMonitor,
        CmdToggleAudio,
        CmdQuitGame,
        CmdLogOff,
        CmdActivateHighPowerSlot1,
        CmdActivateHighPowerSlot2,
        CmdActivateHighPowerSlot3,
        CmdActivateHighPowerSlot4,
        CmdActivateHighPowerSlot5,
        CmdActivateHighPowerSlot6,
        CmdActivateHighPowerSlot7,
        CmdActivateHighPowerSlot8,
        CmdActivateMediumPowerSlot1,
        CmdActivateMediumPowerSlot2,
        CmdActivateMediumPowerSlot3,
        CmdActivateMediumPowerSlot4,
        CmdActivateMediumPowerSlot5,
        CmdActivateMediumPowerSlot6,
        CmdActivateMediumPowerSlot7,
        CmdActivateMediumPowerSlot8,
        CmdActivateLowPowerSlot1,
        CmdActivateLowPowerSlot2,
        CmdActivateLowPowerSlot3,
        CmdActivateLowPowerSlot4,
        CmdActivateLowPowerSlot5,
        CmdActivateLowPowerSlot6,
        CmdActivateLowPowerSlot7,
        CmdActivateLowPowerSlot8,
        CmdOverloadHighPowerSlot1,
        CmdOverloadHighPowerSlot2,
        CmdOverloadHighPowerSlot3,
        CmdOverloadHighPowerSlot4,
        CmdOverloadHighPowerSlot5,
        CmdOverloadHighPowerSlot6,
        CmdOverloadHighPowerSlot7,
        CmdOverloadHighPowerSlot8,
        CmdOverloadMediumPowerSlot1,
        CmdOverloadMediumPowerSlot2,
        CmdOverloadMediumPowerSlot3,
        CmdOverloadMediumPowerSlot4,
        CmdOverloadMediumPowerSlot5,
        CmdOverloadMediumPowerSlot6,
        CmdOverloadMediumPowerSlot7,
        CmdOverloadMediumPowerSlot8,
        CmdOverloadLowPowerSlot1,
        CmdOverloadLowPowerSlot2,
        CmdOverloadLowPowerSlot3,
        CmdOverloadLowPowerSlot4,
        CmdOverloadLowPowerSlot5,
        CmdOverloadLowPowerSlot6,
        CmdOverloadLowPowerSlot7,
        CmdOverloadLowPowerSlot8,
        CmdAccelerate,
        CmdDecelerate,
        CmdStopShip,
        CmdReloadAmmo,
        CmdCloseActiveWindow,
        CmdCloseAllWindows,
        CmdZoomOut,
        CmdZoomIn,
        CmdDronesEngage,
        CmdDronesReturnToBay,
        CmdExitStation,
        OpenDroneBayOfActiveShip,
        OpenCargoHoldOfActiveShip,
        OpenPeopleAndPlaces,
        OpenCharactersheet
    }
}